---
title: "rstan-8schools-example"
author: "roger"
date: "11/14/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
[RStan-Mac-OS-X-Prerequisite-Installation-Instructions]
(https://github.com/stan-dev/rstan/wiki/RStan-Mac-OS-X-Prerequisite-Installation-Instructions)

[RStan-Getting-Started#how-to-use-rstan](https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started#how-to-use-rstan)

```{r setupStan, eval=FALSE}
dotR <- file.path(Sys.getenv("HOME"), ".R")
if (!file.exists(dotR)) dir.create(dotR)
M <- file.path(dotR, "Makevars")
if (!file.exists(M)) file.create(M)
cat("\nCXXFLAGS=-O3", file = M, sep = "\n", append = TRUE)
cat("\nCC=clang", "CXX=clang++ -arch x86_64 -ftemplate-depth-256",
    file = M, sep = "\n", append = TRUE)

Sys.setenv(MAKEFLAGS = "-j4")
install.packages("rstan", repos = "https://cloud.r-project.org/", dependencies=TRUE)
```

After installing, we MUST exit R/RStudio and start up again.

```{r}
schools_dat <- list(J = 8, 
                    y = c(28,  8, -3,  7, -1,  1, 18, 12),
                    sigma = c(15, 10, 16, 11,  9, 11, 10, 18))
library(rstan)
fit8schools <- stan(file = '8schools.stan', data = schools_dat, 
            iter = 1000, chains = 4)
print(fit8schools)
# Some plot functions are not working.
#plot(fit8schools, pars=c("mu", "tau"))
#plot(fit8schools)
pairs(fit8schools, pars = c("mu", "tau", "lp__"))
stan_hist(fit8schools, pars=c("mu","tau"))
stan_hist(fit8schools, pars="theta")
```

`lp__`  is the log posterior

```{r}
la <- extract(fit8schools, permuted = TRUE) # return a list of arrays 
names(la)
mu <- la$mu 
a <- extract(fit8schools, permuted = FALSE) 
str(a)
a2 <- as.array(fit8schools)  ### same as a
m <- as.matrix(fit8schools)

print(fit8schools, digits = 3)
```